spring:
#  profiles:
#    active: test
  application:
    name: doctor-service
  jpa:
    show-sql: true
  h2:
    console:
      enabled: true
  datasource:
    url: jdbc:mysql://localhost:3306/spring_boot_db
    username: root
    password: admin123

  zipkin:
    base-url: http://localhost:9411/

management:
  endpoints:
    web:
      exposure:
        include: "*"


server:
  port: 8100

eureka:
  client:
    service-url:
      default-zone: http://localhost:8761/eureka

#
#
#
#
#spring.application.name=doctor-service
#server.port=8100
#
#spring.jpa.show-sql=true
#spring.h2.console.enabled=true
#
##spring.datasource.url=jdbc:h2:mem:testdb
##spring.datasource.driverClassName=org.h2.Driver
##spring.datasource.username=sa
##spring.datasource.password=
##spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
#
#spring.datasource.url=jdbc:mysql://localhost:3306/spring_boot_db
#spring.datasource.username=root
#spring.datasource.password=admin123
#
#eureka.client.service-url.default-zone=http://localhost:8761/eureka
