spring:
  application:
    name: doctor-service
  jpa:
    show-sql: true
  h2:
    console:
      enabled: true
  datasource:
    url: jdbc:mysql://localhost:3306/spring_boot_db
    username: root
    password: admin123

server:
  port: 8101

eureka:
  client:
    service-url:
      default-zone: http://localhost:8761/eureka
